### ISSUE TITLE
Make default folder configurable

### ISSUE THREAD

**Issue by macjohnny** [MaxServ/t3ext-fal_s3#1]
In order to store fileadmin/ in an s3-bucket, the default upload folder should be configurable.
Currently, the folder is hardcoded to '/' in https://github.com/MaxServ/t3ext-fal_s3/blob/master/Classes/Driver/AmazonS3Driver.php#L181 and https://github.com/MaxServ/t3ext-fal_s3/blob/master/Classes/Driver/AmazonS3Driver.php#L172

**Comment by macjohnny** [comment]
Note: a workaround is the TYPO3 core hook ```$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_userauthgroup.php']['getDefaultUploadFolder']```

**Comment by arnoschoon** [comment]
Hi Esteban,

just to make sure I understand the issue correctly? Are you using the `basePath` configuration to store actual files in a "sub folder" of your S3 bucket?

I think I might have run into the same issue so now I can start looking for a solution. Usually we have separate S3 bucket for each environment and files are stored in the root of the bucket.

The reason we added `basePath` support is to have some kind of nested storage. It might have been luck we didn't run into similar issues.

I'm currently looking for a solution for the `basePath` problem I'm encountering now, hopefully I will be able to fix your issue together with it.

Best regards,
Arno

**Comment by macjohnny** [comment]
hi arno

yes, we are using the `basePath` configuration, however, this is not related to this issue.
We absolutely support the `basePath` property, since it enables you to have an s3 bucket used for multiple purposes, and we also need it in our environment.

The problem is that when uploading a file in the backend to the s3 storage, files should be placed in a sub folder like `user_upload` by default and not to the root of the bucket, as it is hardcoded now. 
For the local storage, this is the case:
https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/core/Classes/Resource/Driver/LocalDriver.php#L214

This affects the behavior if you e.g. add a "text & image" content element in the backend and click the "Select & upload files" button, which will directly upload the files without having you select the upload folder, therefore storing it in the folder returned by `Driver::getDefaultFolder ()`.

**Comment by arnoschoon** [comment]
Hi Esteban,

thanks for the clarification of your issue, the `basePath` issue I encountered earlier was indeed not related. But i managed to fix both this afternoon and released the patch in https://github.com/MaxServ/t3ext-fal_s3/commit/8b54221c2f193fdad1c9f7b3d2c5d20c996ff124 (it should also be available through Packagist by now).

You can specify a default folder for each configured storage, together with the existing `basePath` directive you should be able to arrange the folder structure of the S3 bucket to suit your needs.

```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['fal_s3']['storageConfigurations']['offlineStorage'] = array(
	'bucket' => '',
	'region' => '',
	'key' => '',
	'secret' => '',
	'title' => 'Dummy S3 configuration (offline)',
	'publicBaseUrl' => '',
	'defaultFolder' => 'user_upload',
	'basePath' => '/assets/'
);
```

Rgs, Arno

**Comment by macjohnny** [comment]
awesome, this is exactly what I wanted. thanks a lot!
just a remark: the folder should be defined with leading and trailing slashes, i.e. 'defaultFolder' => '/user_upload/', just to make sure there are no issues with missing slashes / relative paths.

cheers

esteban
