### ISSUE TITLE
upload version 1.1.0 to TER

### ISSUE THREAD

**Issue by macjohnny** [MaxServ/t3ext-fal_s3#2]
hey arno

could you please upload release 1.1.0 to the TER?

**Comment by arnoschoon** [comment]
https://typo3.org/extensions/repository/view/fal_s3 should take a few minutes ;) I almost forgot how uploading to TER worked since I've discovered Packagist :joy:

Rgs, Arno

**Comment by macjohnny** [comment]
thx!

**Comment by Tuurlijk** [comment]
This can be automated: http://release.namelesscoder.net/
