### ISSUE TITLE
TYPO3 8 LTS support

### ISSUE THREAD

**Issue by maechler** [MaxServ/t3ext-fal_s3#31]
We will soon test `fal_s3` on `TYPO3 8 LTS`. Is there a reason to why the upper bound for the TYPO3 version is still `8.5.99` and not `8.7.99`?

We are already using this extension since 1.5 years on a high traffic website and never faced any issues, how about marking the extension state as `stable`?

Thanks anyway for creating and maintaining that awesome extension!

**Comment by haassie** [comment]
Ah I see the version constraint is wrong in the ext_emconf.php. The right constraint is in the composer.json. Will update the ext_emconf.php
