### ISSUE TITLE
Upload new version to TER

### ISSUE THREAD

**Issue by maechler** [MaxServ/t3ext-fal_s3#40]
Could you please upload the newest version to TER?

The version in `ext_emconf.php` should be updated before that:

https://github.com/MaxServ/t3ext-fal_s3/blob/b3f85e4a0c9397fa37de8b54b7f1ff2b5a54a4f6/ext_emconf.php#L12

**Comment by arnoschoon** [comment]
There you go :) https://extensions.typo3.org/extension/fal_s3/

Sorry for the delay, sometimes I forget about TER since Composer brings me so much joy.

**Comment by maechler** [comment]
Perfect, thanks!
