### ISSUE TITLE
Support for TYPO3 11 and 12

### ISSUE THREAD

**Issue by fsuter** [MaxServ/t3ext-fal_s3#72]
Hi. I've seen the open pull request with a big refactoring for achieving compatibility with TYPO3 11. There's also a feature branch, which seems relatively active on that topic. Still that does not give a vision of when such compatibility come happen officially. Is there any plan for a v11 (and ideally v12)-compatible release in the near future?

**Comment by djcprinse** [comment]
Good afternoon @fsuter

Thank you for reaching out. We are currently working at releasing a new version of the extension to add support for TYPO3 v11 and v12.

I can't yet tell when this new version will be available, but it will be available as soon as possible.
